const FREE_PRODUCTS = [
  {
    id: 1,
    name: "Pan Lite",
    category: "Identity",
    description: "Light PAN verification for name and status extraction.",
    trial: 50,
  },
  {
    id: 2,
    name: "Pan Advance",
    category: "Identity",
    description: "Advanced PAN verification with full demographic details.",
    trial: 50,
    preApproved: true,
  },
  {
    id: 3,
    name: "OCR Lite",
    category: "Utility",
    description: "Basic OCR for extracting text from documents.",
    trial: 20,
  },
  {
    id: 4,
    name: "Driving License Advance",
    category: "Utility",
    description: "Full driving license verification with provider check.",
    trial: 50,
    preApproved: true,
  },
  {
    id: 5,
    name: "Voter ID Advance",
    category: "Identity",
    description: "Advanced Voter ID verification with detailed info.",
    trial: 50,
  },
  {
    id: 6,
    name: "GST Advance",
    category: "Financial",
    description: "Advanced GST number verification and validation.",
    trial: 50,
  },
  {
    id: 7,
    name: "Bank Account Verification",
    category: "Financial",
    description: "Check bank account validity and ownership.",
    trial: 50,
  },
  {
    id: 8,
    name: "Pan Demographic",
    category: "Identity",
    description: "Retrieve PAN demographic details for verification.",
    trial: 50,
  },
  {
    id: 9,
    name: "Email Verification",
    category: "Utility",
    description: "Verify email address validity instantly.",
    trial: 50,
  },
  {
    id: 10,
    name: "Phone Verification",
    category: "Utility",
    description: "Verify phone number ownership and status.",
    trial: 50,
  },
  {
    id: 11,
    name: "Address Verification",
    category: "Utility",
    description: "Verify address details against government records.",
    trial: 50,
  },
  {
    id: 12,
    name: "DL Lite",
    category: "Utility",
    description: "Basic driving license verification.",
    trial: 20,
  },
  {
    id: 13,
    name: "Voter ID Lite",
    category: "Identity",
    description: "Basic Voter ID verification.",
    trial: 20,
  },
  {
    id: 14,
    name: "GST Lite",
    category: "Financial",
    description: "Basic GST number verification.",
    trial: 20,
  },
  {
    id: 15,
    name: "OCR Advance",
    category: "Utility",
    description: "Advanced OCR with multi-language support.",
    trial: 50,
    preApproved: true,
  },
  {
    id: 16,
    name: "RC Verification Lite",
    category: "Utility",
    description: "Light RC verification for vehicles.",
    trial: 20,
  },
];

export default FREE_PRODUCTS;
